[build-options]
  observabilityIncluded = true

[package]
  distribution = "2201.3.1"
  export = ["csv_processing"]
  icon = "docs/icon.png"
  keywords = ["Kind/Sample","Type/RestApi","Category/Service","Internal/http"]
  name = "csv_processing"
  org = "choreodemo1210"
  version = "3.1.0"

